<a href="https://colab.research.google.com/github/VanshishChaturvedi/Internship-tbi/blob/main/Practice_task_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Problem Statement:
A data analyst at an e-learning company is onboarding a raw dataset of student exam records. The dataset has data quality issues: some rows have missing marks or missing city entries. The analyst must write a Python function using Pandas that:
* Builds the DataFrame from the inlined data dictionary.
Inspects it with info() and describe().
Counts missing values per column using isnull().sum().
Filters rows where Marks > 75 using Boolean indexing.
Returns a summary dictionary containing:
* "filtered_shape"
* "columns"
* "total_missing"     <br><br>
**Expected Output:**  <br><br>
{   
'filtered_shape': (4, 3),  
'columns': ['Name', 'Marks', 'City'],  
'total_missing': 4   
}

Importing the required libraries

In [31]:
import numpy as np
import pandas as pd

Building the function

In [32]:
def summarise_records():
  data = {
      "Name": ["Student1", "Student2", "Student3", "Student4", "Student5", "Student6", "Student7"],
      "Marks": [52,85,np.nan,95,85,np.nan,76],
      "City": ["City1", "City2", "City3", "City4", "City5", "City6", "City7"]
  }
  df = pd.DataFrame(data)
  print("-"*40)
  print("INFO")
  display(df.info())

  print("-"*40)
  print("DESCRIBE")
  display(df.describe())

  print("-"*40)
  print("Number of missing values per column")
  display(df.isnull().sum())

  print("-"*40)
  print("Students Scoring more than 75 marks")
  filtered_df = df[df["Marks"] > 75]
  display(filtered_df)

  print("-"*40)
  summary = {
      "filtered_shape" : filtered_df.shape,
      "columns": list(df.columns),
      "total_missing" : df.isnull().sum().sum()
  }
  return summary

Calling the Function

In [33]:
summarise_records()

----------------------------------------
INFO
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    7 non-null      object
 1   Marks   5 non-null      float64
 2   City    7 non-null      object
dtypes: float64(1), object(2)
memory usage: 300.0+ bytes

None

----------------------------------------
DESCRIBE

           Marks
count   5.000000
mean   78.600000
std    16.318701
min    52.000000
25%    76.000000
50%    85.000000
75%    85.000000
max    95.000000

----------------------------------------
Number of missing values per column

Name     0
Marks    2
City     0
dtype: int64

----------------------------------------
Students Scoring more than 75 marks

       Name  Marks   City
1  Student2   85.0  City2
3  Student4   95.0  City4
4  Student5   85.0  City5
6  Student7   76.0  City7

----------------------------------------

{'filtered_shape': (4, 3),
 'columns': ['Name', 'Marks', 'City'],
 'total_missing': np.int64(2)}